name: Motes Orchids
favicon: null
layout_spectrum: 0.75205
typography_spectrum: 0.17382
title: Motes Orchids
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffefef'
    - '#3f0118'
    - '#ce5e74'
    - '#9e0e8c'
    - '#6e5d41'
  brandStrength: 0.125
  lightness: 0.8545296017546207
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
