name: Motes Orchids
favicon: null
layout_spectrum: 0.93167
typography_spectrum: 0.34571726177819073
title: Motes Orchids
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#826b6e'
    - '#3a2740'
    - '#f4f3fb'
    - '#c8c2d4'
  brandStrength: 0.125
  lightness: 0.8545296017546207
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
